[package]
name = "anna"
version = "0.1.0"
edition = "2021"
authors = ["Jessica Black <me@jessica.black>"]
license = "MPL-2.0"
publish = false

[dependencies]
clap = { version = "4.5.31", features = ["cargo", "derive", "env"] }
color-eyre = "0.6.3"
winlock = { path = "../winlock" }
