[package]
name = "winlock"
version = "0.1.0"
edition = "2024"
authors = ["Jessica Black <me@jessica.black>"]
license = "MPL-2.0"
public = false

[dependencies]
bon = "3.3.2"
derive_more = { version = "2.0.1", features = ["full"] }
url = "2.5.4"
